import { FeatureCollection } from 'geojson';

export const MRT_DATA: FeatureCollection = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Keat Hong',
        network: 'mrt',
        lines: ['BP3'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Keat_Hong_LRT_Station',
        wikipedia_image_url: null,
        name_zh: '吉丰',
        name_hi: 'கியட் ஹோங்',
      },
      geometry: { type: 'Point', coordinates: [103.74903, 1.378599] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Bangkit',
        network: 'mrt',
        lines: ['BP9'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bangkit_LRT_Station',
        wikipedia_image_url: null,
        name_zh: '万吉',
        name_hi: 'பங்கிட்',
      },
      geometry: { type: 'Point', coordinates: [103.772644, 1.380055] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Petir',
        network: 'mrt',
        lines: ['BP7'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Petir_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/BP7_Petir_LRT_Platform_1.jpg/300px-BP7_Petir_LRT_Platform_1.jpg',
        name_zh: '柏提',
        name_hi: 'பெட்டீர்',
      },
      geometry: { type: 'Point', coordinates: [103.766634, 1.377756] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Jelapang',
        network: 'mrt',
        lines: ['BP12'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Jelapang_LRT_Station',
        wikipedia_image_url: null,
        name_zh: '泽拉邦',
        name_hi: 'ஜெலப்பாங்',
      },
      geometry: { type: 'Point', coordinates: [103.764515, 1.386683] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Teck Whye',
        network: 'mrt',
        lines: ['BP4'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Teck_Whye_LRT_Station',
        wikipedia_image_url: null,
        name_zh: '德惠',
        name_hi: 'டெக் வாய்',
      },
      geometry: { type: 'Point', coordinates: [103.753647, 1.37667] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Choa Chu Kang',
        network: 'mrt',
        lines: ['BP1', 'JS1', 'NS4'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Choa_Chu_Kang_MRT/LRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/NS4_BP1_Choa_Chu_Kang.jpg/300px-NS4_BP1_Choa_Chu_Kang.jpg',
        name_zh: '蔡厝港',
        name_hi: 'சுவா சூ காங்',
      },
      geometry: { type: 'Point', coordinates: [103.744534, 1.384749] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Ten Mile Junction',
        network: 'mrt',
        lines: ['BP14'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Ten_Mile_Junction_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/TenMileJunctionInterior.JPG/300px-TenMileJunctionInterior.JPG',
        name_zh: '十里广场',
        name_hi: 'பத்தாம் கல் சந்திப்பு',
      },
      geometry: { type: 'Point', coordinates: [103.760398, 1.379712] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Phoenix',
        network: 'mrt',
        lines: ['BP5'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Phoenix_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/PhoenixLRTExterior.jpg/300px-PhoenixLRTExterior.jpg',
        name_zh: '凤凰',
        name_hi: 'ஃபீனிக்ஸ்',
      },
      geometry: { type: 'Point', coordinates: [103.758008, 1.378616] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Senja',
        network: 'mrt',
        lines: ['BP13'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Senja_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Senja_LRT_Station%2C_Singapore.jpg/300px-Senja_LRT_Station%2C_Singapore.jpg',
        name_zh: '信佳',
        name_hi: 'சென்ஜா',
      },
      geometry: { type: 'Point', coordinates: [103.762382, 1.382678] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Pending',
        network: 'mrt',
        lines: ['BP8'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Pending_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/BP8_Pending_LRT_Station.jpg/300px-BP8_Pending_LRT_Station.jpg',
        name_zh: '秉定',
        name_hi: 'பெண்டிங்',
      },
      geometry: { type: 'Point', coordinates: [103.771259, 1.376184] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Segar',
        network: 'mrt',
        lines: ['BP11'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Segar_LRT_Station',
        wikipedia_image_url: null,
        name_zh: '实加',
        name_hi: 'செகார்',
      },
      geometry: { type: 'Point', coordinates: [103.769593, 1.387792] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Fajar',
        network: 'mrt',
        lines: ['BP10'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Fajar_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Light_Rail_Transit_train_at_Fajar_LRT_Station%2C_Singapore_-_20060422.jpg/300px-Light_Rail_Transit_train_at_Fajar_LRT_Station%2C_Singapore_-_20060422.jpg',
        name_zh: '法嘉',
        name_hi: 'ஃபஜார்',
      },
      geometry: { type: 'Point', coordinates: [103.7708, 1.38455] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Bukit Panjang',
        network: 'mrt',
        lines: ['BP6', 'DT1'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bukit_Panjang_MRT/LRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/DT1_Bukit_Panjang_MRT.jpg/300px-DT1_Bukit_Panjang_MRT.jpg',
        name_zh: '武吉班让',
        name_hi: 'புக்கிட் பாஞ்சாங்',
      },
      geometry: { type: 'Point', coordinates: [103.762138, 1.378296] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'South View',
        network: 'mrt',
        lines: ['BP2'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/South_View_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/SouthViewLRTStation.JPG/300px-SouthViewLRTStation.JPG',
        name_zh: '南景',
        name_hi: 'சவுத் வியூ',
      },
      geometry: { type: 'Point', coordinates: [103.745285, 1.38026] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Riviera',
        network: 'mrt',
        lines: ['PE4'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Riviera_LRT_Station',
        wikipedia_image_url: null,
        name_zh: '里维拉',
        name_hi: 'ரிவியாரா',
      },
      geometry: { type: 'Point', coordinates: [103.916135, 1.394581] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Damai',
        network: 'mrt',
        lines: ['PE7'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Damai_LRT_station,_Singapore',
        wikipedia_image_url: null,
        name_zh: '达迈',
        name_hi: 'டாமாய்',
      },
      geometry: { type: 'Point', coordinates: [103.908556, 1.405282] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Meridian',
        network: 'mrt',
        lines: ['PE2'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Meridian_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Pe2_meridian.jpg/300px-Pe2_meridian.jpg',
        name_zh: '丽园',
        name_hi: 'மெரிடியன்',
      },
      geometry: { type: 'Point', coordinates: [103.908874, 1.396976] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Oasis',
        network: 'mrt',
        lines: ['PE6'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Oasis_LRT_Station',
        wikipedia_image_url: null,
        name_zh: '绿洲',
        name_hi: 'ஓய்சிஸ்',
      },
      geometry: { type: 'Point', coordinates: [103.912684, 1.402317] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Kadaloor',
        network: 'mrt',
        lines: ['PE5'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Kadaloor_LRT_Station',
        wikipedia_image_url: null,
        name_zh: '卡达鲁',
        name_hi: 'கடலூர்',
      },
      geometry: { type: 'Point', coordinates: [103.916445, 1.399601] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Punggol',
        network: 'mrt',
        lines: ['NE17', 'PTC'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Punggol_MRT/LRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/NE17_PTC_Punggol_Exit_C.jpg/300px-NE17_PTC_Punggol_Exit_C.jpg',
        name_zh: '榜鹅',
        name_hi: 'பொங்கோல்',
      },
      geometry: { type: 'Point', coordinates: [103.902354, 1.405255] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Cove',
        network: 'mrt',
        lines: ['PE1'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Cove_LRT_Station',
        wikipedia_image_url: null,
        name_zh: '海湾',
        name_hi: 'கோவ்',
      },
      geometry: { type: 'Point', coordinates: [103.905852, 1.399464] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Coral Edge',
        network: 'mrt',
        lines: ['PE3'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Coral_Edge_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Coral_Edge_LRT.JPG/300px-Coral_Edge_LRT.JPG',
        name_zh: '珊瑚',
        name_hi: 'கோரல் எட்ஜ்',
      },
      geometry: { type: 'Point', coordinates: [103.912643, 1.393876] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Soo Teck',
        network: 'mrt',
        lines: ['PW7'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Soo_Teck_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Pw7_soo_teck.jpg/300px-Pw7_soo_teck.jpg',
        name_zh: '树德',
        name_hi: 'சூ டெக்',
      },
      geometry: { type: 'Point', coordinates: [103.897237, 1.405394] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Samudera',
        network: 'mrt',
        lines: ['PW4'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Samudera_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Samudera_LRT_View.JPG/300px-Samudera_LRT_View.JPG',
        name_zh: '山姆',
        name_hi: 'சமுத்திரா',
      },
      geometry: { type: 'Point', coordinates: [103.90219, 1.415976] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Sumang',
        network: 'mrt',
        lines: ['PW6'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Sumang_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/en/thumb/3/39/Entrance_A_to_Sumang_LRT_Station.jpg/300px-Entrance_A_to_Sumang_LRT_Station.jpg',
        name_zh: '苏芒',
        name_hi: 'சுமாங்',
      },
      geometry: { type: 'Point', coordinates: [103.898534, 1.408532] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Punggol Point',
        network: 'mrt',
        lines: ['PW3'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Punggol_Point_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Punggol_Point_Platform.jpg/300px-Punggol_Point_Platform.jpg',
        name_zh: '榜鹅坊',
        name_hi: 'பொங்கோல் பாயிண்ட்',
      },
      geometry: { type: 'Point', coordinates: [103.906664, 1.416845] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Teck Lee',
        network: 'mrt',
        lines: ['PW2'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Teck_Lee_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Teck_Lee_Platform.jpg/300px-Teck_Lee_Platform.jpg',
        name_zh: '德利',
        name_hi: 'டெக் லீ',
      },
      geometry: { type: 'Point', coordinates: [103.906653, 1.412705] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Nibong',
        network: 'mrt',
        lines: ['PW5'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Nibong_LRT_Station',
        wikipedia_image_url: null,
        name_zh: '尼蒙',
        name_hi: 'நிபொங்',
      },
      geometry: { type: 'Point', coordinates: [103.900305, 1.411831] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Sam Kee',
        network: 'mrt',
        lines: ['PW1'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Sam_Kee_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Sam_Kee_Entrance.jpg/300px-Sam_Kee_Entrance.jpg',
        name_zh: '三记',
        name_hi: 'சாம் கீ',
      },
      geometry: { type: 'Point', coordinates: [103.904583, 1.40975] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Sengkang',
        network: 'mrt',
        lines: ['NE16', 'STC'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Sengkang_MRT/LRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Sengkang_NEL_Interchange%2C_Nov_05.JPG/300px-Sengkang_NEL_Interchange%2C_Nov_05.JPG',
        name_zh: '盛港',
        name_hi: 'செங்காங்',
      },
      geometry: { type: 'Point', coordinates: [103.895294, 1.39133] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Ranggung',
        network: 'mrt',
        lines: ['SE5'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Ranggung_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Ranggung_LRT_Station_3%2C_Sep_06.JPG/300px-Ranggung_LRT_Station_3%2C_Sep_06.JPG',
        name_zh: '兰岗',
        name_hi: 'ரங்கோங்',
      },
      geometry: { type: 'Point', coordinates: [103.897349, 1.38403] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Rumbia',
        network: 'mrt',
        lines: ['SE2'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Rumbia_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/SE2_Rumbia_Concourse.jpg/300px-SE2_Rumbia_Concourse.jpg',
        name_zh: '棕美',
        name_hi: 'ரூம்பியா',
      },
      geometry: { type: 'Point', coordinates: [103.905937, 1.391509] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Bakau',
        network: 'mrt',
        lines: ['SE3'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bakau_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/SE3_Bakau_Station.jpg/300px-SE3_Bakau_Station.jpg',
        name_zh: '码高',
        name_hi: 'பக்காவ்',
      },
      geometry: { type: 'Point', coordinates: [103.905458, 1.388029] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Compassvale',
        network: 'mrt',
        lines: ['SE1'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Compassvale_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Compassvalelrt.jpg/300px-Compassvalelrt.jpg',
        name_zh: '康埔桦',
        name_hi: 'கம்பஸ்வேல்',
      },
      geometry: { type: 'Point', coordinates: [103.900435, 1.394518] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Kangkar',
        network: 'mrt',
        lines: ['SE4'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Kangkar_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/SE4_Kangkar_station.jpg/300px-SE4_Kangkar_station.jpg',
        name_zh: '港脚',
        name_hi: 'கங்கார்',
      },
      geometry: { type: 'Point', coordinates: [103.902202, 1.383922] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Fernvale',
        network: 'mrt',
        lines: ['SW5'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Fernvale_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Fernvale_LRT_Station_3%2C_Aug_06.JPG/300px-Fernvale_LRT_Station_3%2C_Aug_06.JPG',
        name_zh: '芬微',
        name_hi: 'ஃபொ்ன்வேல்',
      },
      geometry: { type: 'Point', coordinates: [103.876297, 1.391916] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Farmway',
        network: 'mrt',
        lines: ['SW2'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Farmway_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Farmway_LRT_Station%2C_Sep_05.JPG/300px-Farmway_LRT_Station%2C_Sep_05.JPG',
        name_zh: '农道',
        name_hi: 'ஃபாம்வே',
      },
      geometry: { type: 'Point', coordinates: [103.889167, 1.397191] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Kupang',
        network: 'mrt',
        lines: ['SW3'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Kupang_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Kupang_LRT.jpg/300px-Kupang_LRT.jpg',
        name_zh: '古邦',
        name_hi: 'கூப்பாங்',
      },
      geometry: { type: 'Point', coordinates: [103.881244, 1.398204] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Renjong',
        network: 'mrt',
        lines: ['SW8'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Renjong_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Renjong_LRT_Station_2%2C_Aug_06.JPG/300px-Renjong_LRT_Station_2%2C_Aug_06.JPG',
        name_zh: '仁宗',
        name_hi: 'ரெஞ்சோங்',
      },
      geometry: { type: 'Point', coordinates: [103.890485, 1.386708] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Tongkang',
        network: 'mrt',
        lines: ['SW7'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Tongkang_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Tongkang_LRT_Station_2%2C_Aug_06.JPG/300px-Tongkang_LRT_Station_2%2C_Aug_06.JPG',
        name_zh: '同港',
        name_hi: 'தொங்காங்',
      },
      geometry: { type: 'Point', coordinates: [103.885807, 1.389445] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Thanggam',
        network: 'mrt',
        lines: ['SW4'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Thanggam_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ThanggamLRT.JPG/300px-ThanggamLRT.JPG',
        name_zh: '丹甘',
        name_hi: 'தங்கம்',
      },
      geometry: { type: 'Point', coordinates: [103.875645, 1.397434] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Cheng Lim',
        network: 'mrt',
        lines: ['SW1'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Cheng_Lim_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Cheng_Lim_LRT_Station%2C_Sep_05.JPG/300px-Cheng_Lim_LRT_Station%2C_Sep_05.JPG',
        name_zh: '振林',
        name_hi: 'செங் லிம்',
      },
      geometry: { type: 'Point', coordinates: [103.893713, 1.39631] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Layar',
        network: 'mrt',
        lines: ['SW6'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Layar_LRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Layar_LRT_Station_3%2C_Aug_06.JPG/300px-Layar_LRT_Station_3%2C_Aug_06.JPG',
        name_zh: '拉雅',
        name_hi: 'லாயார்',
      },
      geometry: { type: 'Point', coordinates: [103.880074, 1.392114] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Bayfront',
        network: 'mrt',
        lines: ['CE1', 'DT16'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bayfront_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Cross_platform_interchange_of_Bayfront_station.jpg/300px-Cross_platform_interchange_of_Bayfront_station.jpg',
        name_zh: '海湾舫',
        name_hi: 'பேஃபிரண்ட்',
      },
      geometry: { type: 'Point', coordinates: [103.85973, 1.282535] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Farrer Road',
        network: 'mrt',
        lines: ['CC20'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Farrer_Road_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/FRR_platform_level.jpg/300px-FRR_platform_level.jpg',
        name_zh: '花拉路',
        name_hi: 'ஃபேரர் சாலை',
      },
      geometry: { type: 'Point', coordinates: [103.807785, 1.317628] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Nicoll Highway',
        network: 'mrt',
        lines: ['CC5'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Nicoll_Highway_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/NicollHighway-CCLPlatform.JPG/300px-NicollHighway-CCLPlatform.JPG',
        name_zh: '尼诰大道',
        name_hi: 'நிக்கல் நெடுஞ்சாலை',
      },
      geometry: { type: 'Point', coordinates: [103.8635, 1.299671] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Marymount',
        network: 'mrt',
        lines: ['CC16'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Marymount_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/CC16Marymount.jpg/300px-CC16Marymount.jpg',
        name_zh: '玛丽蒙',
        name_hi: 'மேரிமவுண்ட்',
      },
      geometry: { type: 'Point', coordinates: [103.839238, 1.348614] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Dakota',
        network: 'mrt',
        lines: ['CC8'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Dakota_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Dakota_MRT_Platform.jpg/300px-Dakota_MRT_Platform.jpg',
        name_zh: '达科达',
        name_hi: 'டகோட்டா',
      },
      geometry: { type: 'Point', coordinates: [103.88832, 1.308438] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Labrador Park',
        network: 'mrt',
        lines: ['CC27'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Labrador_Park_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/CC27LabradorPark.jpg/300px-CC27LabradorPark.jpg',
        name_zh: '拉柏多公园',
        name_hi: 'லாப்ரடார் பூங்கா',
      },
      geometry: { type: 'Point', coordinates: [103.802782, 1.272328] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'HarbourFront',
        network: 'mrt',
        lines: ['CC29', 'NE1'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/HarbourFront_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/CC29_HarbourFront_station.jpg/300px-CC29_HarbourFront_station.jpg',
        name_zh: '港湾',
        name_hi: 'துறைமுகம்',
      },
      geometry: { type: 'Point', coordinates: [103.822403, 1.265391] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Caldecott',
        network: 'mrt',
        lines: ['CC17', 'TE9'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Caldecott_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Caldecott_MRT_Exit_A.jpg/300px-Caldecott_MRT_Exit_A.jpg',
        name_zh: '加利谷',
        name_hi: 'கால்டிகாட்',
      },
      geometry: { type: 'Point', coordinates: [103.839991, 1.33768] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Dhoby Ghaut',
        network: 'mrt',
        lines: ['CC1', 'NE6', 'NS24'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Dhoby_Ghaut_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Dhoby_Ghaut_MRT_%288643534516%29.jpg/300px-Dhoby_Ghaut_MRT_%288643534516%29.jpg',
        name_zh: '多美歌',
        name_hi: 'டோபி காட்',
      },
      geometry: { type: 'Point', coordinates: [103.84502, 1.298786] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Buona Vista',
        network: 'mrt',
        lines: ['CC22', 'EW21'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Buona_Vista_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Interior_of_the_Circle_Line_section_of_Buona_Vista_MRT_Station%2C_Singapore_-_20110820.jpg/300px-Interior_of_the_Circle_Line_section_of_Buona_Vista_MRT_Station%2C_Singapore_-_20110820.jpg',
        name_zh: '波那维斯达',
        name_hi: 'புவன விஸ்தா',
      },
      geometry: { type: 'Point', coordinates: [103.790838, 1.30719] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Bras Basah',
        network: 'mrt',
        lines: ['CC2'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bras_Basah_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Escalators_in_Bras_Basah_MRT_Station%2C_Singapore.jpg/300px-Escalators_in_Bras_Basah_MRT_Station%2C_Singapore.jpg',
        name_zh: '百胜',
        name_hi: 'பிராஸ் பாசா',
      },
      geometry: { type: 'Point', coordinates: [103.85055, 1.296896] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Esplanade',
        network: 'mrt',
        lines: ['CC3'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Esplanade_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Esplanade-CCLStation.JPG/300px-Esplanade-CCLStation.JPG',
        name_zh: '滨海中心',
        name_hi: 'எஸ்பிளனேட்',
      },
      geometry: { type: 'Point', coordinates: [103.855974, 1.293258] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Tai Seng',
        network: 'mrt',
        lines: ['CC11'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Tai_Seng_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/CC11_Exit_B_Tai_Seng_MRT_station.jpg/300px-CC11_Exit_B_Tai_Seng_MRT_station.jpg',
        name_zh: '大成',
        name_hi: 'தை செங்',
      },
      geometry: { type: 'Point', coordinates: [103.88815, 1.334866] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Stadium',
        network: 'mrt',
        lines: ['CC6'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Stadium_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/CC6_Stadium_MRT_Exit_A.jpg/300px-CC6_Stadium_MRT_Exit_A.jpg',
        name_zh: '体育场',
        name_hi: 'ஸ்டேடியம்',
      },
      geometry: { type: 'Point', coordinates: [103.875402, 1.302778] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Marina Bay',
        network: 'mrt',
        lines: ['CE2', 'NS27', 'TE20'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Marina_Bay_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Circle_Line_Marina_Bay_platform.jpg/300px-Circle_Line_Marina_Bay_platform.jpg',
        name_zh: '滨海湾',
        name_hi: 'மரீனா பே',
      },
      geometry: { type: 'Point', coordinates: [103.854751, 1.275171] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Pasir Panjang',
        network: 'mrt',
        lines: ['CC26'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Pasir_Panjang_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Platform_level_of_Pasir_Panjang_MRT_Station%2C_Singapore_-_20111002.jpg/300px-Platform_level_of_Pasir_Panjang_MRT_Station%2C_Singapore_-_20111002.jpg',
        name_zh: '巴西班让',
        name_hi: 'பாசிர் பாஞ்சாங்',
      },
      geometry: { type: 'Point', coordinates: [103.791614, 1.276177] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Mountbatten',
        network: 'mrt',
        lines: ['CC7'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Mountbatten_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Mountbatten-CCLPlatform.JPG/300px-Mountbatten-CCLPlatform.JPG',
        name_zh: '蒙巴登',
        name_hi: 'மவுண்ட்பேட்டன்',
      },
      geometry: { type: 'Point', coordinates: [103.882496, 1.306249] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Kent Ridge',
        network: 'mrt',
        lines: ['CC24'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Kent_Ridge_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/KentRidgeMRT.JPG/300px-KentRidgeMRT.JPG',
        name_zh: '肯特岗',
        name_hi: 'கெண்ட் ரிஜ்',
      },
      geometry: { type: 'Point', coordinates: [103.784413, 1.293301] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Holland Village',
        network: 'mrt',
        lines: ['CC21'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Holland_Village_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Interior_of_Holland_Village_MRT_Station_-_20111008.jpg/300px-Interior_of_Holland_Village_MRT_Station_-_20111008.jpg',
        name_zh: '荷兰村',
        name_hi: 'ஹாலந்து வில்லேஜ்',
      },
      geometry: { type: 'Point', coordinates: [103.795744, 1.312117] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'one-north',
        network: 'mrt',
        lines: ['CC23'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/One-north_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/CC23one-north.jpg/300px-CC23one-north.jpg',
        name_zh: '纬壹',
        name_hi: 'ஒன்-நார்த்',
      },
      geometry: { type: 'Point', coordinates: [103.787241, 1.299607] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'MacPherson',
        network: 'mrt',
        lines: ['CC10', 'DT26'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/MacPherson_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/MacPhersonMRTExitE.jpg/300px-MacPhersonMRTExitE.jpg',
        name_zh: '麦波申',
        name_hi: 'மெக்பர்சன்',
      },
      geometry: { type: 'Point', coordinates: [103.890306, 1.326567] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Promenade',
        network: 'mrt',
        lines: ['CC4', 'DT15'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Promenade_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/CC%CC%A94_Promenade_Platform_A.jpg/300px-CC%CC%A94_Promenade_Platform_A.jpg',
        name_zh: '宝门廊',
        name_hi: 'புரொமனாட்',
      },
      geometry: { type: 'Point', coordinates: [103.860151, 1.293854] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Lorong Chuan',
        network: 'mrt',
        lines: ['CC14'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Lorong_Chuan_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/LorongChuanStationExitB.jpg/300px-LorongChuanStationExitB.jpg',
        name_zh: '罗弄泉',
        name_hi: 'லோரோங் சுவான்',
      },
      geometry: { type: 'Point', coordinates: [103.863395, 1.351488] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Botanic Gardens',
        network: 'mrt',
        lines: ['CC19', 'DT9'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Botanic_Gardens_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Exit_A_Botanic_Gardens.jpg/300px-Exit_A_Botanic_Gardens.jpg',
        name_zh: '植物园',
        name_hi: 'பூ மலை',
      },
      geometry: { type: 'Point', coordinates: [103.815747, 1.322559] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Telok Blangah',
        network: 'mrt',
        lines: ['CC28'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Telok_Blangah_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/CC28TelokBlangah.jpg/300px-CC28TelokBlangah.jpg',
        name_zh: '直落布兰雅',
        name_hi: 'தெலுக் பிளாங்கா',
      },
      geometry: { type: 'Point', coordinates: [103.809863, 1.270586] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Bartley',
        network: 'mrt',
        lines: ['CC12'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bartley_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Bartley_MRT_Station.jpg/300px-Bartley_MRT_Station.jpg',
        name_zh: '巴特礼',
        name_hi: 'பார்ட்லி',
      },
      geometry: { type: 'Point', coordinates: [103.880449, 1.342438] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Paya Lebar',
        network: 'mrt',
        lines: ['CC9', 'EW8'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Paya_Lebar_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Paya_Lebar_MRT_Station_-_panoramio_%283%29.jpg/300px-Paya_Lebar_MRT_Station_-_panoramio_%283%29.jpg',
        name_zh: '巴耶利峇',
        name_hi: 'பாய லேபார்',
      },
      geometry: { type: 'Point', coordinates: [103.892318, 1.31805] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Serangoon',
        network: 'mrt',
        lines: ['CC13', 'NE12'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Serangoon_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/NE12_Serangoon_Exit_B.jpg/300px-NE12_Serangoon_Exit_B.jpg',
        name_zh: '实龙岗',
        name_hi: 'சிராங்கூன்',
      },
      geometry: { type: 'Point', coordinates: [103.873771, 1.349807] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Haw Par Villa',
        network: 'mrt',
        lines: ['CC25'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Haw_Par_Villa_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/CC25HawParVilla.jpeg/300px-CC25HawParVilla.jpeg',
        name_zh: '虎豹别墅',
        name_hi: 'ஹா பர் வில்லா',
      },
      geometry: { type: 'Point', coordinates: [103.781772, 1.282654] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Bishan',
        network: 'mrt',
        lines: ['CC15', 'NS17'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bishan_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Bishan_MRT_Station_Exit_A.jpg/300px-Bishan_MRT_Station_Exit_A.jpg',
        name_zh: '碧山',
        name_hi: 'பீஷான்',
      },
      geometry: { type: 'Point', coordinates: [103.848263, 1.351455] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Kaki Bukit ',
        network: 'mrt',
        lines: ['DT28'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Kaki_Bukit_MRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/DT28_Kaki_Bukit_station.jpg/300px-DT28_Kaki_Bukit_station.jpg',
        name_zh: '加基武吉',
        name_hi: 'காக்கி புக்கிட்',
      },
      geometry: { type: 'Point', coordinates: [103.908611, 1.335024] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Sixth Avenue',
        network: 'mrt',
        lines: ['DT7'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Sixth_Avenue_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/DT7_Sixth_Avenue_Platform_Basement.jpg/300px-DT7_Sixth_Avenue_Platform_Basement.jpg',
        name_zh: '第六道',
        name_hi: 'சிக்ஸ்த் அவென்யூ',
      },
      geometry: { type: 'Point', coordinates: [103.797225, 1.330591] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Beauty World',
        network: 'mrt',
        lines: ['DT5'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Beauty_World_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Beauty_World_MRT_Station_Exit_B%2C_Singapore%2C_at_night_-_20151114.jpg/300px-Beauty_World_MRT_Station_Exit_B%2C_Singapore%2C_at_night_-_20151114.jpg',
        name_zh: '美世界',
        name_hi: 'பியூட்டி வோர்ல்ட்',
      },
      geometry: { type: 'Point', coordinates: [103.775936, 1.341664] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Upper Changi',
        network: 'mrt',
        lines: ['DT34'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Upper_Changi_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/DT34_Upper_Changi_station.jpg/300px-DT34_Upper_Changi_station.jpg',
        name_zh: '樟宜上段',
        name_hi: 'அப்பர் சாங்கி',
      },
      geometry: { type: 'Point', coordinates: [103.961263, 1.34169] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Little India',
        network: 'mrt',
        lines: ['DT12', 'NE7'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Little_India_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Little_India_Station.jpg/300px-Little_India_Station.jpg',
        name_zh: '小印度',
        name_hi: 'லிட்டில் இந்தியா',
      },
      geometry: { type: 'Point', coordinates: [103.849299, 1.306571] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Mattar',
        network: 'mrt',
        lines: ['DT25'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Mattar_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/DT25_Mattar_station.jpg/300px-DT25_Mattar_station.jpg',
        name_zh: '玛达',
        name_hi: 'மாத்தார்',
      },
      geometry: { type: 'Point', coordinates: [103.882958, 1.326969] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Tampines',
        network: 'mrt',
        lines: ['DT32', 'EW2'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Tampines_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/TampinesMRTEWLandDTL.jpg/300px-TampinesMRTEWLandDTL.jpg',
        name_zh: '淡滨尼',
        name_hi: 'தெம்பினிஸ்',
      },
      geometry: { type: 'Point', coordinates: [103.945084, 1.353374] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Bedok North',
        network: 'mrt',
        lines: ['DT29'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bedok_North_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/DT29_Bedok_North_station.jpg/300px-DT29_Bedok_North_station.jpg',
        name_zh: '勿洛北',
        name_hi: 'பிடோக் நார்த்',
      },
      geometry: { type: 'Point', coordinates: [103.918036, 1.33475] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Stevens',
        network: 'mrt',
        lines: ['DT10', 'TE11'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Stevens_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Stevens_MRT_Station_platform_A.jpg/300px-Stevens_MRT_Station_platform_A.jpg',
        name_zh: '史蒂芬',
        name_hi: 'ஸ்டீவன்ஸ்',
      },
      geometry: { type: 'Point', coordinates: [103.825461, 1.320192] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Tampines East',
        network: 'mrt',
        lines: ['DT33'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Tampines_East_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/DT33_Tampines_East_station.jpg/300px-DT33_Tampines_East_station.jpg',
        name_zh: '淡滨尼东',
        name_hi: 'தெம்பினிஸ் ஈஸ்ட்',
      },
      geometry: { type: 'Point', coordinates: [103.954976, 1.356084] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Ubi ',
        network: 'mrt',
        lines: ['DT27'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Ubi_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/DT27_Ubi_station.jpg/300px-DT27_Ubi_station.jpg',
        name_zh: '乌美',
        name_hi: 'உபி',
      },
      geometry: { type: 'Point', coordinates: [103.899379, 1.329763] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Bencoolen',
        network: 'mrt',
        lines: ['DT21'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bencoolen_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/DT21_Bencoolen_station.jpg/300px-DT21_Bencoolen_station.jpg',
        name_zh: '明古连',
        name_hi: 'பென்கூலன்',
      },
      geometry: { type: 'Point', coordinates: [103.850369, 1.298861] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Newton',
        network: 'mrt',
        lines: ['DT11', 'NS21'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Newton_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Newton_MRT.JPG/300px-Newton_MRT.JPG',
        name_zh: '纽顿',
        name_hi: 'நியூட்டன்',
      },
      geometry: { type: 'Point', coordinates: [103.838864, 1.31296] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Jalan Besar',
        network: 'mrt',
        lines: ['DT22'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Jalan_Besar_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/DT22_Jalan_Besar_station.jpg/300px-DT22_Jalan_Besar_station.jpg',
        name_zh: '惹兰勿刹',
        name_hi: 'ஜாலான் புசார்',
      },
      geometry: { type: 'Point', coordinates: [103.85523, 1.305125] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Fort Canning',
        network: 'mrt',
        lines: ['DT20'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Fort_Canning_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/DT20_Fort_Canning_station.jpg/300px-DT20_Fort_Canning_station.jpg',
        name_zh: '福康宁',
        name_hi: 'ஃபோர்ட் கெனிங்',
      },
      geometry: { type: 'Point', coordinates: [103.844157, 1.292393] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Tan Kah Kee',
        network: 'mrt',
        lines: ['DT8'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Tan_Kah_Kee_MRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/DT8_Tan_Kah_Kee_Platform_with_Students.jpg/300px-DT8_Tan_Kah_Kee_Platform_with_Students.jpg',
        name_zh: '陈嘉庚',
        name_hi: 'டான் கா கீ',
      },
      geometry: { type: 'Point', coordinates: [103.807753, 1.325701] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Tampines West',
        network: 'mrt',
        lines: ['DT31'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Tampines_West_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Tampines_West_Exit_A.jpg/300px-Tampines_West_Exit_A.jpg',
        name_zh: '淡滨尼西',
        name_hi: 'தெம்பினிஸ் வெஸ்ட்',
      },
      geometry: { type: 'Point', coordinates: [103.93856, 1.345519] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Bugis',
        network: 'mrt',
        lines: ['DT14', 'EW12'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bugis_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Exit_B_of_Bugis.jpg/300px-Exit_B_of_Bugis.jpg',
        name_zh: '武吉士',
        name_hi: 'பூகிஸ்',
      },
      geometry: { type: 'Point', coordinates: [103.856095, 1.30053] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Geylang Bahru',
        network: 'mrt',
        lines: ['DT24'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Geylang_Bahru_MRT_Station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/DT24_Geylang_Bahru_Exit_B.jpg/300px-DT24_Geylang_Bahru_Exit_B.jpg',
        name_zh: '芽笼峇鲁',
        name_hi: 'கேலாங் பாரு',
      },
      geometry: { type: 'Point', coordinates: [103.871983, 1.321611] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Bendemeer',
        network: 'mrt',
        lines: ['DT23'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bendemeer_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/DT23_Bendemeer_station.jpg/300px-DT23_Bendemeer_station.jpg',
        name_zh: '明地迷亚',
        name_hi: 'பெண்டிமியர்',
      },
      geometry: { type: 'Point', coordinates: [103.863067, 1.313583] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Cashew',
        network: 'mrt',
        lines: ['DT2'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Cashew_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/en/thumb/1/1b/DT2_Cashew_Platform.JPG/300px-DT2_Cashew_Platform.JPG',
        name_zh: '凯秀',
        name_hi: 'கேஷ்யூ',
      },
      geometry: { type: 'Point', coordinates: [103.764481, 1.369661] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Expo',
        network: 'mrt',
        lines: ['CG1', 'DT35'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Expo_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/DT35_Expo_station.jpg/300px-DT35_Expo_station.jpg',
        name_zh: '博览',
        name_hi: 'எக்ஸ்போ',
      },
      geometry: { type: 'Point', coordinates: [103.962238, 1.33564] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Hillview',
        network: 'mrt',
        lines: ['DT3'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Hillview_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/DT3_Hillview_MRT_Exit_B_by_the_road.jpg/300px-DT3_Hillview_MRT_Exit_B_by_the_road.jpg',
        name_zh: '山景',
        name_hi: 'ஹில்வியூ',
      },
      geometry: { type: 'Point', coordinates: [103.767067, 1.362451] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Chinatown',
        network: 'mrt',
        lines: ['DT19', 'NE4'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Chinatown_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Pagoda_Street_entrance%2C_Chinatown_MRT_Station%2C_2014_%2801%29.JPG/300px-Pagoda_Street_entrance%2C_Chinatown_MRT_Station%2C_2014_%2801%29.JPG',
        name_zh: '牛车水',
        name_hi: 'சைனாடவுன்',
      },
      geometry: { type: 'Point', coordinates: [103.844003, 1.28502] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Downtown',
        network: 'mrt',
        lines: ['DT17'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Downtown_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Exit_E_of_Downtown_MRT_Station_2.jpg/300px-Exit_E_of_Downtown_MRT_Station_2.jpg',
        name_zh: '市中心',
        name_hi: 'டௌன்டவுன்',
      },
      geometry: { type: 'Point', coordinates: [103.853345, 1.279191] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Rochor',
        network: 'mrt',
        lines: ['DT13'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Rochor_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/DT13_Rochor_Exit_B.JPG/300px-DT13_Rochor_Exit_B.JPG',
        name_zh: '梧槽',
        name_hi: 'ரோச்சோர்',
      },
      geometry: { type: 'Point', coordinates: [103.852634, 1.303951] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Bedok Reservoir',
        network: 'mrt',
        lines: ['DT30'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bedok_Reservoir_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Bedok_Reservoir_DTL_Platform.jpg/300px-Bedok_Reservoir_DTL_Platform.jpg',
        name_zh: '勿洛蓄水池',
        name_hi: 'பிடோக் ரெசவோர்',
      },
      geometry: { type: 'Point', coordinates: [103.931887, 1.336284] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Telok Ayer',
        network: 'mrt',
        lines: ['DT18'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Telok_Ayer_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Exit_A_of_Telok_Ayer_MRT_Station.jpg/300px-Exit_A_of_Telok_Ayer_MRT_Station.jpg',
        name_zh: '直落亚逸',
        name_hi: 'தெலுக் ஆயர்',
      },
      geometry: { type: 'Point', coordinates: [103.848744, 1.282123] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'King Albert Park',
        network: 'mrt',
        lines: ['DT6'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/King_Albert_Park_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/DT6_King_Albert_Park_Platform_A.jpg/300px-DT6_King_Albert_Park_Platform_A.jpg',
        name_zh: '阿尔柏王园',
        name_hi: 'கிங் ஆல்பர்ட் பார்க்',
      },
      geometry: { type: 'Point', coordinates: [103.78416, 1.33566] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Raffles Place',
        network: 'mrt',
        lines: ['EW14', 'NS26'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Raffles_Place_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Ns25_rafflesplace.jpg/300px-Ns25_rafflesplace.jpg',
        name_zh: '莱佛士坊',
        name_hi: 'ராஃபிள்ஸ் பிளேஸ்',
      },
      geometry: { type: 'Point', coordinates: [103.85147, 1.284409] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Tuas Crescent',
        network: 'mrt',
        lines: ['EW31'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Tuas_Crescent_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Tuas_Crescent_station.jpg/300px-Tuas_Crescent_station.jpg',
        name_zh: '大士弯',
        name_hi: 'துவாஸ் கிரசண்ட்',
      },
      geometry: { type: 'Point', coordinates: [103.64929, 1.320796] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Tuas Link',
        network: 'mrt',
        lines: ['EW33'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Tuas_Link_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Tuas_Link_station.jpg/300px-Tuas_Link_station.jpg',
        name_zh: '大士连路',
        name_hi: 'துவாஸ் லிங்க்',
      },
      geometry: { type: 'Point', coordinates: [103.636844, 1.340038] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Redhill',
        network: 'mrt',
        lines: ['EW18'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Redhill_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/RedHillMRTfromAbove.jpg/300px-RedHillMRTfromAbove.jpg',
        name_zh: '红山',
        name_hi: 'ரெட்ஹில்',
      },
      geometry: { type: 'Point', coordinates: [103.816757, 1.289653] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'City Hall',
        network: 'mrt',
        lines: ['EW13', 'NS25'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/City_Hall_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/CityHall_MRTStation.jpg/300px-CityHall_MRTStation.jpg',
        name_zh: '政府大厦',
        name_hi: 'நகர மண்டபம்',
      },
      geometry: { type: 'Point', coordinates: [103.852573, 1.293047] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Tanjong Pagar',
        network: 'mrt',
        lines: ['EW15'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Tanjong_Pagar_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/en/thumb/3/3d/TJP_PLAT.JPG/300px-TJP_PLAT.JPG',
        name_zh: '丹戎巴葛',
        name_hi: 'தஞ்சோங் பகார்',
      },
      geometry: { type: 'Point', coordinates: [103.845884, 1.276574] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Lakeside',
        network: 'mrt',
        lines: ['EW26'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Lakeside_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Jurong_LakesideMRT.JPG/300px-Jurong_LakesideMRT.JPG',
        name_zh: '湖畔',
        name_hi: 'ஏரிக்கரை',
      },
      geometry: { type: 'Point', coordinates: [103.720801, 1.344303] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Bedok',
        network: 'mrt',
        lines: ['EW5'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bedok_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/en/thumb/b/b0/Bedok_MRT_Station_platform_A.JPG/300px-Bedok_MRT_Station_platform_A.JPG',
        name_zh: '勿洛',
        name_hi: 'பிடோக்',
      },
      geometry: { type: 'Point', coordinates: [103.929995, 1.323935] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Kallang',
        network: 'mrt',
        lines: ['EW10'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Kallang_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/KAL_PLAT.JPG/300px-KAL_PLAT.JPG',
        name_zh: '加冷',
        name_hi: 'காலாங்',
      },
      geometry: { type: 'Point', coordinates: [103.871339, 1.311448] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Boon Lay',
        network: 'mrt',
        lines: ['EW27', 'JS8'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Boon_Lay_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Boon_Lay_with_PSD.jpg/300px-Boon_Lay_with_PSD.jpg',
        name_zh: '文礼',
        name_hi: 'பூன் லே',
      },
      geometry: { type: 'Point', coordinates: [103.705777, 1.338472] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Aljunied',
        network: 'mrt',
        lines: ['EW9'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Aljunied_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/AljuinedMRT.JPG/300px-AljuinedMRT.JPG',
        name_zh: '阿裕尼',
        name_hi: 'அல்ஜூனிட்',
      },
      geometry: { type: 'Point', coordinates: [103.882882, 1.316484] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Chinese Garden',
        network: 'mrt',
        lines: ['EW25'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Chinese_Garden_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Chinesegarden-mrt.JPG/300px-Chinesegarden-mrt.JPG',
        name_zh: '裕华园',
        name_hi: 'சீனத் தோட்டம்',
      },
      geometry: { type: 'Point', coordinates: [103.732594, 1.34247] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Jurong East',
        network: 'mrt',
        lines: ['EW24', 'JE5', 'NS1'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Jurong_East_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/en/thumb/f/fd/Jurong_East_MRT_Station_with_PSDs.jpg/300px-Jurong_East_MRT_Station_with_PSDs.jpg',
        name_zh: '裕廊东',
        name_hi: 'ஜூரோங் கிழக்கு',
      },
      geometry: { type: 'Point', coordinates: [103.742297, 1.333115] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Dover',
        network: 'mrt',
        lines: ['EW22'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Dover_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Dover_mrt_singapore_z.JPG/300px-Dover_mrt_singapore_z.JPG',
        name_zh: '杜弗',
        name_hi: 'டோவெர்',
      },
      geometry: { type: 'Point', coordinates: [103.778628, 1.311421] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Gul Circle',
        network: 'mrt',
        lines: ['EW30'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Gul_Circle_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Gul_Circle_station.jpg/300px-Gul_Circle_station.jpg',
        name_zh: '卡尔圈',
        name_hi: 'கல் சர்க்கல்',
      },
      geometry: { type: 'Point', coordinates: [103.660415, 1.319423] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Lavender',
        network: 'mrt',
        lines: ['EW11'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Lavender_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/LavenderMRTStation-platform-20050621.jpg/300px-LavenderMRTStation-platform-20050621.jpg',
        name_zh: '劳明达',
        name_hi: 'லவண்டர்',
      },
      geometry: { type: 'Point', coordinates: [103.86303, 1.307445] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Joo Koon',
        network: 'mrt',
        lines: ['EW29'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Joo_Koon_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/SMRT_Siemens_C651_train_at_Joo_Koon_MRT_Station%2C_Singapore_-_20160418-02.jpg/300px-SMRT_Siemens_C651_train_at_Joo_Koon_MRT_Station%2C_Singapore_-_20160418-02.jpg',
        name_zh: '裕群',
        name_hi: 'ஜூ கூன்',
      },
      geometry: { type: 'Point', coordinates: [103.678285, 1.32772] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Eunos',
        network: 'mrt',
        lines: ['EW7'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Eunos_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/EW7_Eunos_Platform.jpg/300px-EW7_Eunos_Platform.jpg',
        name_zh: '友诺士',
        name_hi: 'யூனுஸ்',
      },
      geometry: { type: 'Point', coordinates: [103.903058, 1.319814] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Changi Airport',
        network: 'mrt',
        lines: ['CG2'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Changi_Airport_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/CGA_PLAT.JPG/300px-CGA_PLAT.JPG',
        name_zh: '樟宜机场',
        name_hi: 'சாங்கி விமானநிலையம்',
      },
      geometry: { type: 'Point', coordinates: [103.988565, 1.357338] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Tiong Bahru',
        network: 'mrt',
        lines: ['EW17'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Tiong_Bahru_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Tiong_Bahru_MRT_2016.jpeg/300px-Tiong_Bahru_MRT_2016.jpeg',
        name_zh: '中峇鲁',
        name_hi: 'தியோங் பாரு',
      },
      geometry: { type: 'Point', coordinates: [103.827642, 1.286095] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Pioneer',
        network: 'mrt',
        lines: ['EW28'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Pioneer_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/en/thumb/8/88/Pioneerstn09.JPG/300px-Pioneerstn09.JPG',
        name_zh: '先驱',
        name_hi: 'பயனியர்',
      },
      geometry: { type: 'Point', coordinates: [103.697354, 1.337575] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Tanah Merah',
        network: 'mrt',
        lines: ['', 'CG', 'EW4'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Tanah_Merah_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/C151_tnm_cgl.jpg/300px-C151_tnm_cgl.jpg',
        name_zh: '丹那美拉',
        name_hi: 'தானா மேரா',
      },
      geometry: { type: 'Point', coordinates: [103.946513, 1.327262] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Commonwealth',
        network: 'mrt',
        lines: ['EW20'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Commonwealth_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Commonwealth-mrt.JPG/300px-Commonwealth-mrt.JPG',
        name_zh: '联邦',
        name_hi: 'காமன்வெல்த்',
      },
      geometry: { type: 'Point', coordinates: [103.798308, 1.302443] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Simei',
        network: 'mrt',
        lines: ['EW3'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Simei_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Ew3_Simei.jpg/300px-Ew3_Simei.jpg',
        name_zh: '四美',
        name_hi: 'ஸீமெய்',
      },
      geometry: { type: 'Point', coordinates: [103.953376, 1.343179] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Pasir Ris',
        network: 'mrt',
        lines: ['EW1'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Pasir_Ris_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/PasirRisMRTStation.JPG/300px-PasirRisMRTStation.JPG',
        name_zh: '巴西立',
        name_hi: 'பாசிர் ரிஸ்',
      },
      geometry: { type: 'Point', coordinates: [103.949255, 1.373031] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Outram Park',
        network: 'mrt',
        lines: ['EW16', 'NE3', 'TE17'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Outram_Park_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Outram_Park_Station_East_West_Line_Platform.jpg/300px-Outram_Park_Station_East_West_Line_Platform.jpg',
        name_zh: '欧南园',
        name_hi: 'ஊட்ரம் பார்க்',
      },
      geometry: { type: 'Point', coordinates: [103.840241, 1.280685] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Queenstown',
        network: 'mrt',
        lines: ['EW19'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Queenstown_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Queenstown_MRT_Station_Platform_201401.jpg/300px-Queenstown_MRT_Station_Platform_201401.jpg',
        name_zh: '女皇镇',
        name_hi: 'குவீன்ஸ்டவுன்',
      },
      geometry: { type: 'Point', coordinates: [103.806052, 1.294552] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Kembangan',
        network: 'mrt',
        lines: ['EW6'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Kembangan_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/KBG_PLAT.jpg/300px-KBG_PLAT.jpg',
        name_zh: '景万岸',
        name_hi: 'கெம்பாங்கான்',
      },
      geometry: { type: 'Point', coordinates: [103.912762, 1.321055] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Tuas West Road',
        network: 'mrt',
        lines: ['EW32'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Tuas_West_Road_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Tuas_West_Road_station.jpg/300px-Tuas_West_Road_station.jpg',
        name_zh: '大士西路',
        name_hi: 'துவாஸ் வெஸ்ட் ரோடு',
      },
      geometry: { type: 'Point', coordinates: [103.640149, 1.329495] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Clementi',
        network: 'mrt',
        lines: ['EW23'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Clementi_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Clementi_MRT_Station.jpeg/300px-Clementi_MRT_Station.jpeg',
        name_zh: '金文泰',
        name_hi: 'கிளிமெண்டி',
      },
      geometry: { type: 'Point', coordinates: [103.765231, 1.3151] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Boon Keng',
        network: 'mrt',
        lines: ['NE9'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Boon_Keng_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Ne9boonkeng.jpg/300px-Ne9boonkeng.jpg',
        name_zh: '文庆',
        name_hi: 'பூன் கெங்',
      },
      geometry: { type: 'Point', coordinates: [103.861521, 1.319824] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Farrer Park',
        network: 'mrt',
        lines: ['NE8'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Farrer_Park_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Farrer_Park_MRT_Station%2C_Aug_06.JPG/300px-Farrer_Park_MRT_Station%2C_Aug_06.JPG',
        name_zh: '花拉公园',
        name_hi: 'ஃபேரர் பார்க்',
      },
      geometry: { type: 'Point', coordinates: [103.854377, 1.312708] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Hougang',
        network: 'mrt',
        lines: ['NE14'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Hougang_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/NE14_Hougang_MRT_Exit_A_at_Hougang_Bus_Interchange.jpg/300px-NE14_Hougang_MRT_Exit_A_at_Hougang_Bus_Interchange.jpg',
        name_zh: '后港',
        name_hi: 'ஹவ்காங்',
      },
      geometry: { type: 'Point', coordinates: [103.892754, 1.371904] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Woodleigh',
        network: 'mrt',
        lines: ['NE11'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Woodleigh_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Woodleigh_MRT_Station.JPG/300px-Woodleigh_MRT_Station.JPG',
        name_zh: '兀里',
        name_hi: 'உட்லீ',
      },
      geometry: { type: 'Point', coordinates: [103.870754, 1.339197] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Buangkok',
        network: 'mrt',
        lines: ['NE15'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Buangkok_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Ne15_buangkok2.jpg/300px-Ne15_buangkok2.jpg',
        name_zh: '万国',
        name_hi: 'புவாங்கோக்',
      },
      geometry: { type: 'Point', coordinates: [103.89305, 1.383056] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Kovan',
        network: 'mrt',
        lines: ['NE13'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Kovan_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/NE13_Kovan_Exit_C.jpg/300px-NE13_Kovan_Exit_C.jpg',
        name_zh: '高文',
        name_hi: 'கோவன்',
      },
      geometry: { type: 'Point', coordinates: [103.884874, 1.359977] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Potong Pasir',
        network: 'mrt',
        lines: ['NE10'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Potong_Pasir_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Ne10potongpasir.jpg/300px-Ne10potongpasir.jpg',
        name_zh: '波东巴西',
        name_hi: 'போத்தோங் பாசிர்',
      },
      geometry: { type: 'Point', coordinates: [103.869093, 1.331254] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Clarke Quay',
        network: 'mrt',
        lines: ['NE5'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Clarke_Quay_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Clarke_Quay_MRT_Station%2C_Aug_06.JPG/300px-Clarke_Quay_MRT_Station%2C_Aug_06.JPG',
        name_zh: '克拉码头',
        name_hi: 'கிளார்க் கீ',
      },
      geometry: { type: 'Point', coordinates: [103.846869, 1.288981] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Bukit Gombak',
        network: 'mrt',
        lines: ['NS3'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bukit_Gombak_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Bukit_Gombak_MRT_Station%2C_2015.jpg/300px-Bukit_Gombak_MRT_Station%2C_2015.jpg',
        name_zh: '武吉甘柏',
        name_hi: 'புக்கிட் கோம்பாக்',
      },
      geometry: { type: 'Point', coordinates: [103.751825, 1.358893] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Sembawang',
        network: 'mrt',
        lines: ['NS11'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Sembawang_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/NS11_Sembawang_Exit_A_at_angle.jpg/300px-NS11_Sembawang_Exit_A_at_angle.jpg',
        name_zh: '三巴旺',
        name_hi: 'செம்பாவாங்',
      },
      geometry: { type: 'Point', coordinates: [103.820056, 1.449093] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Marina South Pier',
        network: 'mrt',
        lines: ['NS28'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Marina_South_Pier_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Marina_South_Pier_Station.JPG/300px-Marina_South_Pier_Station.JPG',
        name_zh: '滨海南码头',
        name_hi: 'மரினா சவுத் படகுத்துறை',
      },
      geometry: { type: 'Point', coordinates: [103.862723, 1.27175] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Kranji',
        network: 'mrt',
        lines: ['NS7'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Kranji_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/NS7_Kranji_Exit_A.jpg/300px-NS7_Kranji_Exit_A.jpg',
        name_zh: '克兰芝',
        name_hi: 'கிராஞ்சி',
      },
      geometry: { type: 'Point', coordinates: [103.761989, 1.425219] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Novena',
        network: 'mrt',
        lines: ['NS20'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Novena_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Ns20_novena.jpg/300px-Ns20_novena.jpg',
        name_zh: '诺维娜',
        name_hi: 'நொவீனா',
      },
      geometry: { type: 'Point', coordinates: [103.843492, 1.320084] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Admiralty',
        network: 'mrt',
        lines: ['NS10'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Admiralty_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/NS10_Admiralty_MRT_Platform.jpg/300px-NS10_Admiralty_MRT_Platform.jpg',
        name_zh: '海军部',
        name_hi: 'அட்மிரல்ட்டி',
      },
      geometry: { type: 'Point', coordinates: [103.800959, 1.440637] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Toa Payoh',
        network: 'mrt',
        lines: ['NS19'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Toa_Payoh_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Toapayohmrtplatform.jpg/300px-Toapayohmrtplatform.jpg',
        name_zh: '大巴窑',
        name_hi: 'தோ பாயோ',
      },
      geometry: { type: 'Point', coordinates: [103.847327, 1.332297] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Bukit Batok',
        network: 'mrt',
        lines: ['NS2'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Bukit_Batok_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/BukitBatokMRT.JPG/300px-BukitBatokMRT.JPG',
        name_zh: '武吉巴督',
        name_hi: 'புக்கிட் பாத்தோக்',
      },
      geometry: { type: 'Point', coordinates: [103.749591, 1.349057] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Marsiling',
        network: 'mrt',
        lines: ['NS8'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Marsiling_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/MarsilingMRT.JPG/300px-MarsilingMRT.JPG',
        name_zh: '马西岭',
        name_hi: 'மார்சிலிங்',
      },
      geometry: { type: 'Point', coordinates: [103.774216, 1.432542] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Yio Chu Kang',
        network: 'mrt',
        lines: ['NS15'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Yio_Chu_Kang_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Platform_screen_doors_at_Yio_Chu_Kang_MRT_station%2C_Singapore.jpg/300px-Platform_screen_doors_at_Yio_Chu_Kang_MRT_station%2C_Singapore.jpg',
        name_zh: '杨厝港',
        name_hi: 'இயோ சூ காங்',
      },
      geometry: { type: 'Point', coordinates: [103.844965, 1.38178] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Ang Mo Kio',
        network: 'mrt',
        lines: ['NS16'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Ang_Mo_Kio_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/NS16_Ang_Mo_Kio_Platform_A-2.jpg/300px-NS16_Ang_Mo_Kio_Platform_A-2.jpg',
        name_zh: '宏茂桥',
        name_hi: 'அங் மோ கியோ',
      },
      geometry: { type: 'Point', coordinates: [103.84954, 1.370053] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Somerset',
        network: 'mrt',
        lines: ['NS23'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Somerset_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/SomersetMRTStation.jpg/300px-SomersetMRTStation.jpg',
        name_zh: '索美塞',
        name_hi: 'சாமர்செட்',
      },
      geometry: { type: 'Point', coordinates: [103.838504, 1.300328] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Yew Tee',
        network: 'mrt',
        lines: ['NS5'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Yew_Tee_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/NS5_Yew_Tee_Platform.jpg/300px-NS5_Yew_Tee_Platform.jpg',
        name_zh: '油池',
        name_hi: 'இயூ டீ',
      },
      geometry: { type: 'Point', coordinates: [103.747401, 1.397461] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Braddell',
        network: 'mrt',
        lines: ['NS18'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Braddell_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/NS18_Braddell_Exit_A.jpg/300px-NS18_Braddell_Exit_A.jpg',
        name_zh: '布莱德',
        name_hi: 'பிரேடல்',
      },
      geometry: { type: 'Point', coordinates: [103.846788, 1.340599] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Yishun',
        network: 'mrt',
        lines: ['NS13'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Yishun_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Yishun_MRT_Station_with_PSDs.jpg/300px-Yishun_MRT_Station_with_PSDs.jpg',
        name_zh: '义顺',
        name_hi: 'யீஷூன்',
      },
      geometry: { type: 'Point', coordinates: [103.835028, 1.429384] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Orchard',
        network: 'mrt',
        lines: ['NS22', 'TE14'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Orchard_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Orchard_C151b.jpg/300px-Orchard_C151b.jpg',
        name_zh: '乌节',
        name_hi: 'ஆர்ச்சர்ட்',
      },
      geometry: { type: 'Point', coordinates: [103.831982, 1.303223] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Khatib',
        network: 'mrt',
        lines: ['NS14'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Khatib_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/KhatibMRT.JPG/300px-KhatibMRT.JPG',
        name_zh: '卡迪',
        name_hi: 'காதிப்',
      },
      geometry: { type: 'Point', coordinates: [103.832998, 1.417316] },
    },
    {
      type: 'Feature',
      properties: {
        type: 'station',
        name: 'Woodlands',
        network: 'mrt',
        lines: ['NS9', 'TE2'],
        wikipedia_url: 'https://en.wikipedia.org/wiki/Woodlands_MRT_station',
        wikipedia_image_url:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/NS9_Woodlands_Exit_A.jpg/300px-NS9_Woodlands_Exit_A.jpg',
        name_zh: '兀兰',
        name_hi: 'ஊட்லண்ட்ஸ்',
      },
      geometry: { type: 'Point', coordinates: [103.787675, 1.437388] },
    },
  ],
};

export const MRT_COLORS: Record<string, string> = {
  BP: '#748477',
  PE: '#748477',
  SE: '#748477',
  CC: '#F79F07',
  DT: '#03529F',
  EW: '#009D57',
  NE: '#851197',
  NS: '#DF2518',
};
